repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-PyYAML
          - types-lxml
        # Balanced settings for gradual type adoption
        args: [
            --ignore-missing-imports, # Ignore imports that can't be resolved
            --allow-untyped-defs, # Allow functions without type annotations
            --allow-untyped-calls, # Allow calling functions without type annotations
            --allow-subclassing-any, # Allow subclassing Any typed classes
            --allow-untyped-decorators, # Allow decorators without type annotations
            --allow-incomplete-defs, # Allow incomplete type annotations in functions
            --implicit-optional, # Allow None as an implicit Optional
            --disable-error-code=var-annotated, # Disable errors about missing variable annotations
            --disable-error-code=union-attr, # Disable union attribute access errors
            --disable-error-code=operator, # Disable operator type errors
            --disable-error-code=index, # Disable indexing type errors
            --disable-error-code=return-value, # Disable return value type errors
            --disable-error-code=assignment, # Disable assignment type errors
            --warn-redundant-casts, # Warn about redundant type casts
            --warn-unreachable, # Warn about unreachable code
            --pretty, # Prettier error messages
          ]
        exclude: ^tests/
  - repo: https://github.com/google/keep-sorted
    rev: v0.6.0
    hooks:
      - id: keep-sorted
