[project]
name = "migri-assistant"
version = "0.1.0"
description = "AI assistant specialized in knowledge from Migri.fi"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Finntegrate Team"}
]
dependencies = [
    "chromadb>=1.0.4",
    "litellm>=1.66.1",
    "typer>=0.15.2",
    "scrapy>=2.12.0",
    "rich>=13.7.0",  # For better CLI output formatting
]

[project.scripts]
migri-scrape = "migri_assistant.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["migri_assistant"]

[tool.black]
line-length = 88
target-version = ["py312"]
