name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync --dev

      - name: Lint with Ruff
        run: |
          source .venv/bin/activate
          uv ruff . --check

      - name: Test with pytest and coverage
        run: |
          source .venv/bin/activate
          uv run pytest --cov=migri_assistant --cov-report=xml --cov-report=term

      - name: Check coverage threshold
        run: |
          source .venv/bin/activate
          coverage_result=$(uv run coverage report | tail -1 | awk '{print $NF}' | sed 's/%//')
          echo "Coverage: $coverage_result%"
          if (( $(echo "$coverage_result < 80" | bc -l) )); then
            echo "❌ Coverage threshold not met: $coverage_result% is less than 80%"
            exit 1
          else
            echo "✅ Coverage threshold met: $coverage_result% is greater than or equal to 80%"
          fi
